'use strict';

'require form';
'require view';

return view.extend({
	render: function() {
		var m, s, o;

		m = new form.Map('safeshield', _('SafeShield'),
			_('Configure SafeShield options that are safe to change from LuCI. Device identity is generated by SafeShield, and SmartSafeHub endpoints are package-managed rather than user-editable settings.'));

		s = m.section(form.NamedSection, 'config', 'safeshield', _('SafeShield settings'));
		s.addremove = false;
		s.anonymous = true;

		s.tab('general', _('General'));
		s.tab('rules', _('Local allow/block'));
		s.tab('dns', _('DNS'));
		s.tab('advanced', _('Advanced'));
		s.tab('debug', _('Debug'));

		/*
		 * User-facing settings
		 *
		 * Keep this tab small. Values such as device_fingerprint, device_vendor,
		 * device_model, device_arch and device_memory_mb are runtime/device identity
		 * values. They should be generated idempotently by SafeShield on first run,
		 * not edited from LuCI.
		 */
		o = s.taboption('general', form.Flag, 'enabled', _('Enable SafeShield'));
		o.default = '1';
		o.rmempty = false;

		o = s.taboption('general', form.Value, 'license_key', _('License key'));
		o.password = true;
		o.rmempty = true;
		o.description = _('Used by SafeShield to authorize artifact resolution and downloads.');

		o = s.taboption('general', form.Flag, 'refresh_on_boot', _('Refresh on boot'));
		o.default = '1';
		o.rmempty = false;
		o.description = _('Download and install the latest SafeShield artifact when the router boots.');

		o = s.taboption('general', form.Value, 'refresh_interval_s', _('Refresh interval'));
		o.datatype = 'uinteger';
		o.placeholder = '82800';
		o.rmempty = false;
		o.description = _('Interval in seconds between automatic artifact refreshes.');

		/*
		 * Local rules. These paths are still advanced-ish, but they are part of the
		 * product feature surface because Phase 0 needs custom allow/block logic.
		 */
		o = s.taboption('rules', form.Flag, 'apply_local_overrides', _('Apply local allow/block lists'));
		o.default = '1';
		o.rmempty = false;
		o.description = _('Apply local allowlist and blocklist entries on top of the downloaded artifact.');

		o = s.taboption('rules', form.Value, 'local_allowlist_path', _('Local allowlist path'));
		o.placeholder = '/etc/safeshield/allowlist';
		o.rmempty = true;
		o.description = _('Domains listed here are removed from the final blocklist.');

		o = s.taboption('rules', form.Value, 'local_blocklist_path', _('Local blocklist path'));
		o.placeholder = '/etc/safeshield/blocklist';
		o.rmempty = true;
		o.description = _('Domains listed here are added to the final blocklist.');

		/*
		 * DNS integration. Expose these separately because changing them can break
		 * DNS resolution, but they are still useful for OpenWrt administrators.
		 */
		o = s.taboption('dns', form.Value, 'dnsmasq_instance', _('dnsmasq instance'));
		o.placeholder = '*';
		o.rmempty = true;
		o.description = _('Target dnsmasq instance. Use * for the default/common setup.');

		o = s.taboption('dns', form.Value, 'dns', _('dnsmasq config file'));
		o.placeholder = 'dnsmasq.conf';
		o.rmempty = true;
		o.description = _('Low-level dnsmasq configuration filename used by SafeShield. Leave unchanged unless you know why this is needed.');

		o = s.taboption('dns', form.Flag, 'require_wan', _('Require WAN before refresh'));
		o.default = '1';
		o.rmempty = false;
		o.description = _('Wait for WAN connectivity before resolving and downloading artifacts.');

		o = s.taboption('dns', form.Flag, 'dnsmasq_sanity_check', _('Run dnsmasq sanity check'));
		o.default = '1';
		o.rmempty = false;
		o.description = _('Validate dnsmasq state after installing the blocklist.');

		/*
		 * Artifact validation and runtime safety knobs.
		 */
		o = s.taboption('advanced', form.Value, 'max_blocklist_file_size_kb', _('Maximum blocklist size'));
		o.datatype = 'uinteger';
		o.placeholder = '30000';
		o.rmempty = false;
		o.description = _('Maximum accepted artifact size in KB.');

		o = s.taboption('advanced', form.Value, 'min_valid_line_count', _('Minimum valid rule count'));
		o.datatype = 'uinteger';
		o.placeholder = '3000';
		o.rmempty = false;
		o.description = _('Reject artifacts that contain fewer valid dnsmasq rules than this value.');

		o = s.taboption('advanced', form.Flag, 'compress_blocklist', _('Compress blocklist'));
		o.default = '0';
		o.rmempty = false;
		o.description = _('Keep disabled unless the SafeShield runtime explicitly supports compressed dnsmasq blocklists.');

		o = s.taboption('advanced', form.Flag, 'initial_dnsmasq_restart', _('Restart dnsmasq before install'));
		o.default = '0';
		o.rmempty = false;
		o.description = _('Restart dnsmasq before installing a newly downloaded artifact. Normally this should stay disabled.');

		o = s.taboption('advanced', form.Value, 'download_timeout', _('Download timeout'));
		o.datatype = 'uinteger';
		o.placeholder = '10';
		o.rmempty = false;
		o.description = _('Artifact download timeout in seconds.');

		o = s.taboption('advanced', form.Value, 'download_retry', _('Download retries'));
		o.datatype = 'uinteger';
		o.placeholder = '3';
		o.rmempty = false;

		o = s.taboption('advanced', form.Value, 'pause_timeout', _('Pause timeout'));
		o.datatype = 'uinteger';
		o.placeholder = '20';
		o.rmempty = false;
		o.description = _('Maximum time in seconds to wait while SafeShield is paused.');

		o = s.taboption('advanced', form.Value, 'boot_start_delay_s', _('Boot start delay'));
		o.datatype = 'uinteger';
		o.placeholder = '30';
		o.rmempty = false;
		o.description = _('Delay in seconds before SafeShield starts work during boot.');

		/*
		 * Diagnostics.
		 */
		o = s.taboption('debug', form.ListValue, 'verbosity', _('Log verbosity'));
		o.value('0', _('Errors only'));
		o.value('1', _('Warnings'));
		o.value('2', _('Info'));
		o.value('3', _('Debug'));
		o.default = '2';
		o.rmempty = false;

		o = s.taboption('debug', form.Flag, 'debug', _('Enable debug logging'));
		o.default = '0';
		o.rmempty = false;
		o.description = _('Enable additional debug output for troubleshooting. Keep disabled in normal production use.');

		return m.render();
	}
});
